// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: coach.sql

package sqlc

import (
	"context"
	"database/sql"
)

const editCoach = `-- name: EditCoach :one
UPDATE coach
SET fullname = $2
WHERE coach_id = $1
RETURNING coach_id, fullname, email, country, title, company, numberofcandidate, password
`

type EditCoachParams struct {
	CoachID  int64          `json:"coach_id"`
	Fullname sql.NullString `json:"fullname"`
}

func (q *Queries) EditCoach(ctx context.Context, arg EditCoachParams) (Coach, error) {
	row := q.db.QueryRowContext(ctx, editCoach, arg.CoachID, arg.Fullname)
	var i Coach
	err := row.Scan(
		&i.CoachID,
		&i.Fullname,
		&i.Email,
		&i.Country,
		&i.Title,
		&i.Company,
		&i.Numberofcandidate,
		&i.Password,
	)
	return i, err
}

const getCoach = `-- name: GetCoach :one
SELECT coach_id, fullname, email, country, title, company, numberofcandidate, password FROM coach
WHERE coach_id = $1 LIMIT 1
`

func (q *Queries) GetCoach(ctx context.Context, coachID int64) (Coach, error) {
	row := q.db.QueryRowContext(ctx, getCoach, coachID)
	var i Coach
	err := row.Scan(
		&i.CoachID,
		&i.Fullname,
		&i.Email,
		&i.Country,
		&i.Title,
		&i.Company,
		&i.Numberofcandidate,
		&i.Password,
	)
	return i, err
}

const getCoachByEmail = `-- name: GetCoachByEmail :one
SELECT coach_id, fullname, email, country, title, company, numberofcandidate, password FROM coach
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCoachByEmail(ctx context.Context, email sql.NullString) (Coach, error) {
	row := q.db.QueryRowContext(ctx, getCoachByEmail, email)
	var i Coach
	err := row.Scan(
		&i.CoachID,
		&i.Fullname,
		&i.Email,
		&i.Country,
		&i.Title,
		&i.Company,
		&i.Numberofcandidate,
		&i.Password,
	)
	return i, err
}

const registerCoach = `-- name: RegisterCoach :one
INSERT INTO coach
(email, password) VALUES ($1, $2) RETURNING coach_id, fullname, email, country, title, company, numberofcandidate, password
`

type RegisterCoachParams struct {
	Email    sql.NullString `json:"email"`
	Password string         `json:"password"`
}

func (q *Queries) RegisterCoach(ctx context.Context, arg RegisterCoachParams) (Coach, error) {
	row := q.db.QueryRowContext(ctx, registerCoach, arg.Email, arg.Password)
	var i Coach
	err := row.Scan(
		&i.CoachID,
		&i.Fullname,
		&i.Email,
		&i.Country,
		&i.Title,
		&i.Company,
		&i.Numberofcandidate,
		&i.Password,
	)
	return i, err
}
