// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Candidate struct {
	CanID       int64          `json:"can_id"`
	Fullname    sql.NullString `json:"fullname"`
	Title       sql.NullString `json:"title"`
	Email       sql.NullString `json:"email"`
	Country     sql.NullString `json:"country"`
	Ranklocal   sql.NullInt32  `json:"ranklocal"`
	Rankworld   sql.NullInt32  `json:"rankworld"`
	Company     sql.NullString `json:"company"`
	Dateofbirth time.Time      `json:"dateofbirth"`
	CoachID     sql.NullInt64  `json:"coach_id"`
	Password    string         `json:"password"`
	IsInTeam    sql.NullBool   `json:"is_in_team"`
}

type Challenge struct {
	ChalID  int64          `json:"chal_id"`
	ComID   sql.NullInt32  `json:"com_id"`
	Name    sql.NullString `json:"name"`
	Stime   time.Time      `json:"stime"`
	Etime   time.Time      `json:"etime"`
	Maxteam sql.NullInt32  `json:"maxteam"`
}

type Coach struct {
	CoachID           int64          `json:"coach_id"`
	Fullname          sql.NullString `json:"fullname"`
	Email             sql.NullString `json:"email"`
	Country           sql.NullString `json:"country"`
	Title             sql.NullString `json:"title"`
	Company           sql.NullString `json:"company"`
	Numberofcandidate sql.NullInt32  `json:"numberofcandidate"`
	Password          string         `json:"password"`
}

type Competition struct {
	ComID          int64          `json:"com_id"`
	Name           sql.NullString `json:"name"`
	Decription     sql.NullString `json:"decription"`
	Rules          sql.NullString `json:"rules"`
	Agelimit       sql.NullInt32  `json:"agelimit"`
	Images         []string       `json:"images"`
	Status         sql.NullString `json:"status"`
	Stime          time.Time      `json:"stime"`
	Etime          time.Time      `json:"etime"`
	Registerstart  time.Time      `json:"registerstart"`
	Registerend    time.Time      `json:"registerend"`
	Location       sql.NullString `json:"location"`
	Venue          sql.NullString `json:"venue"`
	Address        sql.NullString `json:"address"`
	City           sql.NullString `json:"city"`
	MaxTeamSize    sql.NullInt32  `json:"max_team_size"`
	ParticipantFee sql.NullInt32  `json:"participant_fee"`
	FirstPrize     sql.NullInt32  `json:"first_prize"`
	SecondPrize    sql.NullInt32  `json:"second_prize"`
	ThirdPrize     sql.NullInt32  `json:"third_prize"`
	OrgID          sql.NullInt64  `json:"org_id"`
}

type Organization struct {
	OrgID       int64          `json:"org_id"`
	Name        sql.NullString `json:"name"`
	Logo        sql.NullString `json:"logo"`
	Description sql.NullString `json:"description"`
}

type Team struct {
	TeamID       int64          `json:"team_id"`
	CoachID      sql.NullInt64  `json:"coach_id"`
	JoinCode     sql.NullString `json:"join_code"`
	Teamname     sql.NullString `json:"teamname"`
	CompetitonID sql.NullInt32  `json:"competiton_id"`
	Maxteam      sql.NullInt32  `json:"maxteam"`
}

type TeamCandidate struct {
	TeamID           int64          `json:"team_id"`
	CanID            int64          `json:"can_id"`
	InvitationStatus sql.NullString `json:"invitation_status"`
}
