// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Candicate struct {
	CanID       int64          `json:"can_id"`
	Fullname    sql.NullString `json:"fullname"`
	Title       sql.NullString `json:"title"`
	Email       sql.NullString `json:"email"`
	Country     sql.NullString `json:"country"`
	Ranklocal   sql.NullInt32  `json:"ranklocal"`
	Rankworld   sql.NullInt32  `json:"rankworld"`
	Company     sql.NullString `json:"company"`
	Dateofbirth time.Time      `json:"dateofbirth"`
	CoachID     sql.NullInt32  `json:"coach_id"`
}

type Challenge struct {
	ChalID  int64          `json:"chal_id"`
	ComID   sql.NullInt32  `json:"com_id"`
	Name    sql.NullString `json:"name"`
	Stime   time.Time      `json:"stime"`
	Etime   time.Time      `json:"etime"`
	Maxteam sql.NullInt32  `json:"maxteam"`
}

type Coach struct {
	CoachID  int64          `json:"coach_id"`
	Fullname sql.NullString `json:"fullname"`
	Email    sql.NullString `json:"email"`
	Country  sql.NullString `json:"country"`
	Title    sql.NullString `json:"title"`
	Company  sql.NullString `json:"company"`
}

type Competition struct {
	ComID      int64          `json:"com_id"`
	Name       sql.NullString `json:"name"`
	Stime      time.Time      `json:"stime"`
	Etime      time.Time      `json:"etime"`
	Decription sql.NullString `json:"decription"`
	Rules      sql.NullString `json:"rules"`
	Agelimit   sql.NullInt32  `json:"agelimit"`
	Prizevalue sql.NullString `json:"prizevalue"`
}

type Team struct {
	TeamID       int64          `json:"team_id"`
	CoachID      sql.NullInt32  `json:"coach_id"`
	MemberID     sql.NullInt32  `json:"member_id"`
	Teamname     sql.NullString `json:"teamname"`
	CompetitonID sql.NullInt32  `json:"competiton_id"`
}
