DROP TABLE IF EXISTS team_candidate;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS coach;
DROP TABLE IF EXISTS candidate;
DROP TABLE IF EXISTS challenges;
DROP TABLE IF EXISTS competition;
DROP TABLE IF EXISTS organization;